# Generated by Django 4.2.5 on 2023-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idAct', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
